import type { Metadata } from 'next';
import React from 'react';
import './globals.css';
import { Sidebar } from '@/components/ui/Sidebar/Sidebar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Sidebar />
				{children}
			</body>
		</html>
	);
}
