name: Deploy Frontend

on:
  push:
    branches:
      - main
      - feature/secret-chat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: ssh root@194.58.114.226 "cd /safe_chat/secret_chat-frontend && git pull && pnpm install && pnpm build && pm2 restart frontend"
